### ISSUE TITLE
Can't build on Ubuntu 18.04.2 Docker 18.09.6

### ISSUE THREAD

**Issue by pmury** [kubevirt/libvirt#24]
Hi, all, 
the build works mostly fine as I can judge but as it seems shortly before end I get this error (running build.sh):

```
(...)
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : python3-dnf-plugins-core-2.1.5-4.fc28.noarch           1/2 
  Installing       : dnf-plugins-core-2.1.5-4.fc28.noarch                   2/2 
  Running scriptlet: dnf-plugins-core-2.1.5-4.fc28.noarch                   2/2 
  Verifying        : dnf-plugins-core-2.1.5-4.fc28.noarch                   1/2 
  Verifying        : python3-dnf-plugins-core-2.1.5-4.fc28.noarch           2/2 

Installed:
  dnf-plugins-core.noarch 2.1.5-4.fc28                                          
  python3-dnf-plugins-core.noarch 2.1.5-4.fc28                                  

Complete!
Repository successfully enabled.
Copr repo for virt-preview owned by @virtmaint- 206 kB/s | 218 kB     00:01    
Last metadata expiration check: 0:00:00 ago on Tue May 28 09:34:23 2019.
No match for argument: libvirt-daemon-kvm-5.1.0
No match for argument: libvirt-client-5.1.0
Error: Unable to find a match
The command '/bin/sh -c dnf install -y dnf-plugins-core &&   dnf copr enable -y @virtmaint-sig/virt-preview &&   dnf install -y     libvirt-daemon-kvm-${LIBVIRT_VERSION}     libvirt-client-${LIBVIRT_VERSION}     socat     genisoimage     selinux-policy selinux-policy-targeted     augeas &&   dnf clean all' returned a non-zero code: 1
```

**Comment by nertpinx** [comment]
Yes, this is because the virt-preview repository is (probably) not keeping old libvirt versions around, however kubevirt sticks to a particular version. @crobinso could know whether the versions are kept in there or not. @fabiand, @rmohr or @cynepco3hahue could tell you more about the versioning, whether this just needs to be updated or if we need to figure out how to stick to old releases.

**Comment by rmohr** [comment]
We have now a CDN. There are more dependencies which disappear from time-to-time, not just libvirt. My preferred solution right now is to upload all dependencies to a CDN automatically and have another process which periodically updates to newer versions. This will ensure consistency but also that we get the new things.

**Comment by rmohr** [comment]
@pmury to build in your case, just change this line to a working version: https://github.com/kubevirt/libvirt/blob/master/Dockerfile#L6

**Comment by 1605200517** [comment]
5.3.0 works, thank you!

**Comment by pmury** [comment]
5.3.0 works for me, thanks!
