### ISSUE TITLE
/host-dev does not exist

### ISSUE THREAD

**Issue by synergiator** [kubevirt/libvirt#25]
With libvirt 5.3.0, I get the following error on container start:

```
+ mkdir /dev.container
+ mount --rbind /dev /dev.container
+ mount --rbind /host-dev /dev
mount: /dev: special device /host-dev does not exist.

```
What should be /host-dev?

**Comment by Queuecumber** [comment]
I had to add two more volumes: `/dev:/host-dev ` and `/sys:/host-sys` for it to work. Since none of this is in the documentation I assume I'm doing something wrong
