### ISSUE TITLE
Any chance for an update to the libvirt version.

### ISSUE THREAD

**Issue by brianberzins** [kubevirt/libvirt#31]
Currently the libvert version is hard coded to 5.0.0 and there are changes in 5.1.0 (from March) that detect cephFS as a shared filed system to support live migration.

Troubleshooting got me here:
```
{
  "component": "virt-launcher",
  "kind": "",
  "level": "error",
  "msg": "Live migration failed",
  "name": "ubuntu-desktop",
  "namespace": "cdi",
  "pos": "manager.go:476",
  "reason": "virError(Code=81, Domain=10, Message='Unsafe migration: Migration without shared storage is unsafe')",
  "timestamp": "2019-11-04T22:23:28.314583Z",
  "uid": "1f294436-c3e8-4a7a-a352-0bbe1c14a3a5"
}
```
Which lead me through:
1. https://bugzilla.redhat.com/show_bug.cgi?id=1665553
1. https://github.com/libvirt/libvirt/commit/6dd2a2ae6386b1d51edcc9a434f56d7f9dc2cb35
1. https://www.libvirt.org/news.html#v5.1.0
1. https://github.com/kubevirt/libvirt/blob/master/Dockerfile#L6

Libvert 5.0.0 is from January, and it would be greatly appreciated to have this bumped up and released.

**Comment by rmohr** [comment]
#39 got merged.  https://github.com/kubevirt/kubevirt/pull/2893 will make use of the new container.

**Comment by brianberzins** [comment]
@rmohr Thank you so much!
Greatly appreciate your time and effort to make this happen!
