### ISSUE TITLE
Docs should clarify a build is required

### ISSUE THREAD

**Issue by andrewrynhard** [kubevirt/libvirt#34]
```
$ docker pull kubevirt/libvirtd:latest
Error response from daemon: pull access denied for kubevirt/libvirtd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by andreabolognani** [comment]
> $ docker pull kubevirt/libvirtd:latest
> Error response from daemon: pull access denied for kubevirt/libvirtd, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

It's just a typo in the name of the container: try with `kubevirt/libvirt` instead, it should work. You're still going to get an old image, though: for the current one, you should pull `kubevirt/libvirt@sha256:840d4502f48f567f9030e22ba8aa8294003f1ac20b6a0c06c01b0236a8964a3a`.

I'm addressing the documentation issue as part of https://github.com/kubevirt/libvirt/pull/35.

**Comment by andreabolognani** [comment]
@andrewrynhard it should be okay now: see https://github.com/kubevirt/libvirt/#versions-to-use

If you're satisfied with the new documentation, please consider closing the issue; if not, let me know how I can improve it further! :)

**Comment by andrewrynhard** [comment]
Thanks 👍.
