### ISSUE TITLE
kubevirt/libvirt image for ARM

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/libvirt#49]
Hi guys, Currently, I am trying kubevirt on ARM, and met some qemu errors in kubevirt/libvirt.
1. the qemu-kvm binary for arm64 does not support "vga" device.
2. The edk2 package on arm64 for UEFI boot does not put loader and nvram in following location.   
`EFIPath                = "/usr/share/OVMF/OVMF_CODE.fd"
EFIVarsPath            = "/usr/share/OVMF/OVMF_VARS.fd"`
I tried to install qemu from fedora official repo rather from "@virtmaint-sig/for-kubevirt-version" in Dockerfile. Everything runs well, in spite of the size of kubevirt/libvirt image expand from around 600M to 1.3G.

Here are two questions.
1. Where can I find any information on build for package in @virtmaint-sig/for-kubevirt? Are there any projects? 
2. I found the kubevirt/libvirt in dockerhub is out of date. The qemu-kvm version is 3.1.0 while it has updated to 4.1.0 in source code. Does the image still under maintaining?

Looking forward your reply.

**Comment by zhlhahaha** [comment]
ping @rmohr 
cc @lubinsz

**Comment by andreabolognani** [comment]
What image are you using?

kubevirt/libvirt:av-8.1-20191203-930921c is the one with the freshest packages, and specifically it contains QEMU 4.1.0.

We're also in the process of getting a new build out, which hopefully won't take much longer; the new image will have QEMU 4.2.0.

**Comment by zhlhahaha** [comment]
> What image are you using?
> 
> kubevirt/libvirt:av-8.1-20191203-930921c is the one with the freshest packages, and specifically it contains QEMU 4.1.0.
> 
> We're also in the process of getting a new build out, which hopefully won't take much longer; the new image will have QEMU 4.2.0.

Thanks Andrea for your reply. I was using kubevirt/libvirt:latest, and it contain QEMU 3.1.0.
I have tried kubevirt/libvirt:av-8.1-20191203-930921c on **ARM**, it works find, but this qemu-kvm binary still does not support VGA device. I run following commands on ARM server.
`#docker run -it --entrypoint "/bin/bash" kubevirt/libvirt:av-8.1-20191203-930921c`
`[root@111a1d1c09d9 /]#/usr/libexec/qemu-kvm -M virt -device help`
`...`
`name "virtserialport", bus virtio-serial-bus`

`Display devices:`
`name "virtio-gpu-device", bus virtio-bus`
`name "virtio-gpu-pci", bus PCI, alias "virtio-gpu"`

`Misc devices:`
`...`
In spite of Display devices, many other devices does not support by this qemu-kvm binary on **ARM**, such as Network device, Storage device and so forth.
I think this issue may be caused by qemu-kvm binary compiling process. 
As the binary comes from packages in "@virtmaint-sig/for-kubevirt-version", I am wandering if there is any detailed information about the library.
Looking forward your reply.

**Comment by andreabolognani** [comment]
> Thanks Andrea for your reply. I was using kubevirt/libvirt:latest, and it contain QEMU 3.1.0.

Yeah, unfortunately `latest` is not the one with the newest contents, which is fairly confusing. We should probably consider not generating that tag and let users pick a version explicitly instead.

> I have tried kubevirt/libvirt:av-8.1-20191203-930921c on **ARM**, it works find, but this qemu-kvm binary still does not support VGA device. I run following commands on ARM server.
> `#docker run -it --entrypoint "/bin/bash" kubevirt/libvirt:av-8.1-20191203-930921c`
> `[root@111a1d1c09d9 /]#/usr/libexec/qemu-kvm -M virt -device help`
> `...`
> `name "virtserialport", bus virtio-serial-bus`
> 
> `Display devices:`
> `name "virtio-gpu-device", bus virtio-bus`
> `name "virtio-gpu-pci", bus PCI, alias "virtio-gpu"`
> 
> `Misc devices:`
> `...`

VGA is problematic on ARM, because of some issues with cache coherency; virtio-gpu can be used instead, and with recent Linux guests it should give a good experience out of the box. See [this blog post](https://www.kraxel.org/blog/2019/09/display-devices-in-qemu/) for more information.

> In spite of Display devices, many other devices does not support by this qemu-kvm binary on **ARM**, such as Network device, Storage device and so forth.

You should have all devices you need: `virtio-net` for networking, `virtio-blk` for storage, and so on. Is there a specific device that you're interested and is not available?

> I think this issue may be caused by qemu-kvm binary compiling process.
> As the binary comes from packages in "@virtmaint-sig/for-kubevirt-version", I am wandering if there is any detailed information about the library.

Many devices are disabled in those builds. If you want to know the details, your best bet is to look at the spec file and corresponding patches directly.

**Comment by zhlhahaha** [comment]
Thanks @andreabolognani, very informative and detailed reply. 
Currently I only meet VGA device error when start vm via vm-cirros.yaml in kubevirt project on ARM. and no request for other devices. 
If we have requests for devices in the future, should I post issue here? Or can I ask you directly?

**Comment by andreabolognani** [comment]
> Currently I only meet VGA device error when start vm via vm-cirros.yaml in kubevirt project on ARM. and no request for other devices.

I'm not sure how far along aarch64 support in KubeVirt is, but it's entirely possible that some features are simply not implemented across all architectures yet, and that there are rough edges.

> If we have requests for devices in the future, should I post issue here? Or can I ask you directly?

Please open an issue. Speaking of which, do you think we can close this one now? :)

**Comment by zhlhahaha** [comment]
> > Currently I only meet VGA device error when start vm via vm-cirros.yaml in kubevirt project on ARM. and no request for other devices.
> 
> I'm not sure how far along aarch64 support in KubeVirt is, but it's entirely possible that some features are simply not implemented across all architectures yet, and that there are rough edges.
> 
> > If we have requests for devices in the future, should I post issue here? Or can I ask you directly?
> 
> Please open an issue. Speaking of which, do you think we can close this one now? :)

Yes, I will close it. Thanks.

**Comment by wonleing** [comment]
> You should have all devices you need: virtio-net for networking, virtio-blk for storage, and so on. Is there a specific device that you're interested and is not available?

Do mouse and keyboard need such driver on arm64? We manage to add virtio-gpu, but the vm doesn't have mouse and keyboard for input..
