### ISSUE TITLE
Define uid and gid of libvirt in the Dockerfile

### ISSUE THREAD

**Issue by rmohr** [kubevirt/libvirt#5]
To allow other containers to connect via sockets as non-root, we need to explicitly set the uid and gid of the libvirt user and group. Otherwise it is hard to guarantee that the other container can connect.

**Comment by fabiand** [comment]
That was actually the reason why I hoped we could go with tcp-only for libvirt ocnnections.

But it seems that the socker based cgroup detection requires the socket.

@rmohr but why does the uid/gid needs to be set for socket connections?

**Comment by berrange** [comment]
This is not required. Just makes the socket mode 0777, and then turn on SASL with scram-sha-1 to enable username + password auth of libvirtd. Then given virt-handler the username + password via a libvirtd auth config file, which we can populate using a k8s secret.

**Comment by rmohr** [comment]
@berrange sounds reasonable. Closing it in favour of #6

**Comment by fabiand** [comment]
Nice.
