### ISSUE TITLE
Remove 'latest' tag

### ISSUE THREAD

**Issue by andreabolognani** [kubevirt/libvirt#54]
Since we have multiple streams that can be updated in parallel, depending on which build happens to have run last it might not point to the freshest contents; additionally, with the recent changes made to the container build workflow, the tag is no longer updated and will thus become increasingly obsolete over time.

KubeVirt itself only ever refers to images by sha, so we can remove it safely with no loss in functionality.

@rmohr can you take care of that?

**Comment by rmohr** [comment]
Done.

/close

**Comment by andreabolognani** [comment]
@rmohr thanks! :)
