### ISSUE TITLE
Change socket file permissions and enable SASL for authentication

### ISSUE THREAD

**Issue by rmohr** [kubevirt/libvirt#6]
To quote @berrange  from https://github.com/kubevirt/libvirt/issues/5#issuecomment-313613532:

> [...] makes the socket mode 0777, and then turn on SASL with scram-sha-1 to enable username + password auth of libvirtd. Then given virt-handler the username + password via a libvirtd auth config file, which we can populate using a k8s secret.

This way it is very easy to run other agents on the host or in other containers as non-root and give them the possibility to connect to the socket..

**Comment by nertpinx** [comment]
/remove-lifecycle rotten
Still keeping this in mind, I worked on a script, but it didn't do everything.

**Comment by nertpinx** [comment]
I wasn't successful, unfortunately, but I have a couple of ideas. If someone wants to look into this, feel free to bounce ideas off of me.

**Comment by rmohr** [comment]
/close

Not relevant anymore. virt-launcher talks with its own libvirtd and if someone enters the container, the password is in the container for virt-launcher already.
