### ISSUE TITLE
drop libvirt-daemon-driver-storage for libvirt v6.9.0+

### ISSUE THREAD

**Issue by crobinso** [kubevirt/libvirt#61]
Currently [Dockerfile.in](https://github.com/kubevirt/libvirt/blob/av-8.2/Dockerfile.in) explicitly pulls in `libvirt-daemon-driver-storage` even though kubevirt is not making use of the libvirt storage driver. This is to workaround a libvirt bug, fixed by [this commit](https://gitlab.com/libvirt/libvirt/-/commit/accdc0e7730739f398e392c23bc8380d3574a878) which should be in not-yet-released libvirt v6.9.0.

This issue is a reminder to drop libvirt-daemon-driver-storage from the image once we update to a new enough libvirt version

**Comment by andreabolognani** [comment]
Created https://github.com/kubevirt/kubevirt/issues/4825 to track this now that we have bazeldnf taking care of installing packages.
