### ISSUE TITLE
Cover more virt packages?

### ISSUE THREAD

**Issue by andreabolognani** [kubevirt/libvirt#66]
Looking at [virt-preview](https://copr.fedorainfracloud.org/coprs/g/virtmaint-sig/virt-preview/packages/), there are a bunch of packages that are relevant to KubeVirt's needs but are not pinned to specific versions using special COPRs the same way we do for QEMU and libvirt. I'm thinking specifically about the various firmwares, and possibly virglrenderer.

@crobinso, do you think it would make sense to extend your scripts so that they cover those packages as well?

**Comment by crobinso** [comment]
In kubevirt-copr I enabled seabios, SLOF, and edk2 now which AFAICT are the only ones that kubevirt may care about. Possibly ipxe too but that's pretty stable in Fedora.

Personally though on kubevirt container side I would not be in a rush to stick to specific versions. Generally for the roms it's considered newer the better, they are always backwards compatible with older qemu, and rom versions are not tied to specific qemu versions. But they are published now if the need ever arises.

**Comment by andreabolognani** [comment]
There is an overall desire for reproducibility, which is partially defeated when packages are installed from Fedora repositories as those contents can change at any time. Simply mirroring the contents, which the build system of the main repository already has support for, is part of the solution. Of course it's a blurry line, but I think in general it's a good idea to have full control of at least the packages that are unequivocally virt-specific.
