### ISSUE TITLE
Add supported devices for qemu-kvm in kubevirt/libvirt image for ARM

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/libvirt#77]
Currently, I am verifing the e2e tests of KubeVirt on Arm64, and some test cases used following devices, however these devices are not supported by qemu-kvm on Arm64. Shall we add support for these devices? @andreabolognani Thanks a lot.

Storage devices:
name "ide-cd", bus IDE, desc "virtual IDE CD-ROM"
name "ide-drive", bus IDE, desc "virtual IDE disk or CD-ROM (legacy)"
name "ide-hd", bus IDE, desc "virtual IDE disk"

Misc devices:
name "i6300esb", bus PCI

**Comment by andreabolognani** [comment]
> Currently, I am verifing the e2e tests of KubeVirt on Arm64, and some test cases used following devices, however these devices are not supported by qemu-kvm on Arm64. Shall we add support for these devices? @andreabolognani Thanks a lot.

Note that we're no longer using this repository: libvirt / QEMU builds are taken directly from CentOS Stream 8, so if we need to add support for any device that's where the change should happen.

> Storage devices:
> name "ide-cd", bus IDE, desc "virtual IDE CD-ROM"
> name "ide-drive", bus IDE, desc "virtual IDE disk or CD-ROM (legacy)"
> name "ide-hd", bus IDE, desc "virtual IDE disk"

IDE is not a thing on aarch64 AFAIK, so I wouldn't expect these to be present.

> Misc devices:
> name "i6300esb", bus PCI

You left out the description for this device, which is "Intel 6300ESB". So this is an Intel part, which I would find a bit weird on an aarch64 VM. Does an architecture-agnostic alternative not exist?

**Comment by zhlhahaha** [comment]
Hi, Andrea, thanks for your quick reply.

> IDE is not a thing on aarch64 AFAIK, so I wouldn't expect these to be present.

I do not quite understand why "IDE is not a thing on aarch64", as the bus is not real hardware but emulated by qemu.
I request these devices because I get the following error message when trying to add SATA file to VM on KubeVirt, 
`SATA is not supported with this QEMU binary`
I tried to add SATA via libvirt on my bare-metal server, I saw it uses ide-hd bus, like following, so I think if we can make qemu support for the ide related device.
`-device ide-hd,bus=sata0.1,drive=drive-sata0-0-1,id=sata0-0-1`
Shall we add ide-hd device support or just disable sata on Arm64?

> description for this device, which is "Intel 6300ESB". So this is an Intel part, which I would find a bit weird on an aarch64 VM.

As this device is a watchdog device, and just emulated via qemu, so I think it is fine. Despite "Intel 6300ESB", I think it would be better to support at least one watchdog device, like ib700. How's your idea?

>  libvirt / QEMU builds are taken directly from CentOS Stream 8

Do you know where we can send requests to add support for devices?

**Comment by andreabolognani** [comment]
> I do not quite understand why "IDE is not a thing on aarch64", as the bus is not real hardware but emulated by qemu. I request these devices because I get the following error message when trying to add SATA file to VM on KubeVirt, `SATA is not supported with this QEMU binary` I tried to add SATA via libvirt on my bare-metal server, I saw it uses ide-hd bus, like following, so I think if we can make qemu support for the ide related device. `-device ide-hd,bus=sata0.1,drive=drive-sata0-0-1,id=sata0-0-1` Shall we add ide-hd device support or just disable sata on Arm64?

Right, I keep forgetting that "ide-hd" is also used for SATA disks. I find the name confusing, but there must be some reason for it.

Anyway, I just don't see the point of using emulated devices such as SATA when paravirtualized Virtio devices will work. Is there any specific reason why you need a SATA disk specifically?

Note that the SATA controller itself (ich9-ahci aka ahci) is an Intel-specific part.

> As this device is a watchdog device, and just emulated via qemu, so I think it is fine. Despite "Intel 6300ESB", I think it would be better to support at least one watchdog device, like ib700. How's your idea?

I'm surprised that a more generic watchdog device is not available in QEMU. Perhaps we should consider implementing one? A few years back the pcie-root-port device was introduced as an architecture-agnostic replacement for the Intel-specific ioh3420, for example.

And you're right that there is nothing preventing i6300esb from working with aarch64/virt, assuming the guest OS has drivers for it, but it's just weird when you run "lspci" in your Arm VM and the string "Intel" shows up :) That's the main reason why I would prefer a generic version to be created instead.

> Do you know where we can send requests to add support for devices?

CentOS Stream 8 is still a sort of downstream of RHEL, so the [Red Hat Enterprise Linux Advanced Virtualization product](https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%20Advanced%20Virtualization) would be the right place.

**Comment by zhlhahaha** [comment]
> Anyway, I just don't see the point of using emulated devices such as SATA when paravirtualized Virtio devices will work. Is there any specific reason why you need a SATA disk specifically?

Yes, in the KubeVirt e2e tests, some files is attached to VM using SATA bus, like secret, configmap and so forth. I am not sure why they do so, I will ask Roman.
```
		<disk device="disk" type="file">
			<source file="/var/run/kubevirt-private/config-map-disks/configmap-bbqwh.iso"></source>
			<target bus="sata" dev="sda"></target>
			<driver cache="none" error_policy="stop" io="native" name="qemu" type="raw" discard="unmap"></driver>
			<alias name="ua-configmap-bbqwh"></alias>
			<expandDisksEnabled>true</expandDisksEnabled>
		</disk>
		<disk device="disk" type="file">
			<source file="/var/run/kubevirt-private/secret-disks/secret-222mq.iso"></source>
			<target bus="sata" dev="sdb"></target>
			<driver cache="none" error_policy="stop" io="native" name="qemu" type="raw" discard="unmap"></driver>
			<alias name="ua-secret-222mq"></alias>
			<expandDisksEnabled>true</expandDisksEnabled>
		</disk>
		<disk device="disk" type="file">
			<source file="/var/run/kubevirt-private/service-account-disk/service-account.iso"></source>
			<target bus="sata" dev="sdc"></target>
			<driver cache="none" error_policy="stop" io="native" name="qemu" type="raw" discard="unmap"></driver>
			<alias name="ua-default-disk"></alias>
			<expandDisksEnabled>true</expandDisksEnabled>
		</disk>
		<disk device="disk" type="file">
			<source file="/var/run/kubevirt-private/downwardapi-disks/downwardapi-bcxxb.iso"></source>
			<target bus="sata" dev="sdd"></target>
			<driver cache="none" error_policy="stop" io="native" name="qemu" type="raw" discard="unmap"></driver>
			<alias name="ua-downwardapi-bcxxb"></alias>
			<expandDisksEnabled>true</expandDisksEnabled>
		</disk>
```


> Perhaps we should consider implementing one? A few years back the pcie-root-port device was introduced as an architecture-agnostic replacement for the Intel-specific ioh3420, for example.

Great, but for some legal issue, my team is not allowed to submit PR to qemu. Do you have some interesting on imply this? Or I can send a proposal to Linaro.

> CentOS Stream 8 is still a sort of downstream of RHEL, so the Red Hat Enterprise Linux Advanced Virtualization product would be the right place.

Thanks!

**Comment by andreabolognani** [comment]
> Yes, in the KubeVirt e2e tests, some files is attached to VM using SATA bus, like secret, configmap and so forth. I am not sure why they do so, I will ask Roman.

I wonder if it's only a few of the tests doing that, in which case we could simply skip those on Arm, or if using any of the features you mentioned always require SATA. The latter doesn't sound too good even from an x86_64 perspective: you might be stuck with SATA in certain cases, like for example Windows guests, but aside from those it should always be preferable to use Virtio.

> > Perhaps we should consider implementing one? A few years back the pcie-root-port device was introduced as an architecture-agnostic replacement for the Intel-specific ioh3420, for example.
> 
> Great, but for some legal issue, my team is not allowed to submit PR to qemu. Do you have some interesting on imply this? Or I can send a proposal to Linaro.

I have no experience working on QEMU so I wouldn't be a great candidate for this. But you can open a bug against the Red Hat Enterprise Linux Advanced Virtualization product and discuss there what the best way forward is when it comes to making a watchdog device available to Arm VMs.

**Comment by zhlhahaha** [comment]
> I wonder if it's only a few of the tests doing that, in which case we could simply skip those on Arm,

I have check the source code, kubevirt set SATA as default disk bus, and I have submitted a PR to make SCSI as default disk bus on Arm64. https://github.com/kubevirt/kubevirt/pull/7007

> But you can open a bug against the Red Hat Enterprise Linux Advanced Virtualization product and discuss there what the best way forward is when it comes to making a watchdog device available to Arm VMs.

Thanks for your suggestion!
