### ISSUE TITLE
Add release tags when building latest

### ISSUE THREAD

**Issue by rmohr** [kubevirt/libvirt#9]
When we merge a commit, travis builds the container and pushed it to docker hub. 

The optimal way would be to reflect the libvirt version (and maybe build timestamp) in the tag. We could achive that, by first creating the image, then asking libvirt for the installed version. Then we just upload the appropriate tag too.

We can then regularly use the latest libvirt version in kubevirt/kubevirt, but if soemthing goes wrong, people can fall back to an older build.

**Comment by davidvossel** [comment]
I'd suggest using both the libvirt version and the commit hash.

So something like this.
```
kubevirt/libvirt:<libvirt-version>.<commit-hash>
```
The idea with the commit hash is it prevents us from ever clobbering the same tag with a new build for any reason.

**Comment by fabiand** [comment]
+1 on the hash suffix.

date suffix would have worked as well. Might be mroe informative?

**Comment by nertpinx** [comment]
The commit hash is fine unless there is someone pulling the latest kubevirt/libvirt in which case the commit hash would get sorted alphabetically, right?

**Comment by fabiand** [comment]
The hash would be an issue if we do more than one build for a given libvirt version.then there is a risk.

Thus maybe build date is better.

Actually, in oVirt Node for images we used:
ovirt-engine-appliance-4.2-20180629.1.fc27

In order to track content better.

For images like base images such a structure seems good, because it is more than a single binary you track.

**Comment by fabiand** [comment]
Taking that approach I'd suggest

```
kubevirt/libvirt:<libvirt-version>.<date>

```

**Comment by nertpinx** [comment]
+1 multiple rebuilds in one day will get rewritten instead of polluting the "storage". I'll look into that.

**Comment by rmohr** [comment]
> +1 multiple rebuilds in one day will get rewritten instead of polluting the "storage". I'll look into that.

That would mean that we would test against one libvirt/qemu version and when someone deploys kubevirt 3 hours later, another libvirt/qemu version might be used. Please don't override tags (except latest).

**Comment by fabiand** [comment]
+1 for not overwriting.

My main motivation was to keep it sortable and avoid collissions.

We probably want to have year,month,day,hour,min

**Comment by nertpinx** [comment]
Or just `kubevirt/libvirt:<libvirt-version>.<build-number>`?

**Comment by fabiand** [comment]
Well. You need to maintain the build number .. if we change the system etc.

Date is monotonic moving fwd (hpefully) thus as good as a build nuber.

**Comment by nertpinx** [comment]
True. So if time is preferred, then I'll select some compact format and we can continue the discussion of the particular format on the PR. Thanks for all the suggestions.

**Comment by fabiand** [comment]
Any luck with this?

**Comment by nertpinx** [comment]
/remove-lifecycle rotten
Still keeping this in my head.
